---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: provision-cluster
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster and obtains a kubeconfig.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  tasks:
    - name: provision-eaas-space
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
    - name: provision-cluster
      runAfter:
        - provision-eaas-space
      taskSpec:
        results:
          - name: clusterName
            value: "$(steps.create-cluster.results.clusterName)"
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(steps.get-supported-versions.results.versions[0])."
          - name: create-cluster
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-create-ephemeral-cluster-hypershift-aws/0.1/eaas-create-ephemeral-cluster-hypershift-aws.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: version
                value: "$(steps.pick-version.results.version)"
              - name: imageContentSources
                value: "- source: registry.redhat.io/rhtas/rhtas-rhel9-operator\n  mirrors:\n    - quay.io/securesign/rhtas-operator\n- source: registry.redhat.io/rhtas/trillian-logsigner-rhel9\n  mirrors:\n    - quay.io/securesign/trillian-logsigner\n- source: registry.redhat.io/rhtas/trillian-logserver-rhel9\n  mirrors:\n    - quay.io/securesign/trillian-logserver\n- source: registry.redhat.io/rhtas/trillian-database-rhel9\n  mirrors:\n    - quay.io/securesign/trillian-database\n- source: registry.redhat.io/rhtas/fulcio-rhel9\n  mirrors:\n    - quay.io/securesign/fulcio-server\n- source: registry.redhat.io/rhtas/trillian-redis-rhel9\n  mirrors:\n    - quay.io/securesign/trillian-redis\n- source: registry.redhat.io/rhtas/rekor-server-rhel9\n  mirrors:\n    - quay.io/securesign/rekor-server\n- source: registry.redhat.io/rhtas/rekor-search-ui-rhel9\n  mirrors:\n    - quay.io/securesign/rekor-search-ui\n- source: registry.redhat.io/rhtas/rekor-backfill-redis-rhel9\n  mirrors:\n    - quay.io/securesign/trillian-redis\n- source: registry.redhat.io/rhtas/tuf-server-rhel9\n  mirrors:\n    - quay.io/securesign/scaffold-tuf-server\n- source: registry.redhat.io/rhtas/certificate-transparency-rhel9\n  mirrors:\n    - quay.io/securesign/certificate-transparency-go\n- source: registry.redhat.io/rhtas/client-server-cg-rhel9\n  mirrors:\n    - quay.io/securesign/cli-client-server-cg\n- source: registry.redhat.io/rhtas/client-server-re-rhel9\n  mirrors:\n    - quay.io/securesign/client-server-re\n- source: registry.redhat.io/rhtas/segment-reporting-rhel9\n  mirrors:\n    - quay.io/securesign/segment-backup-job\n- source: registry.redhat.io/rhtas/timestamp-authority-rhel9\n  mirrors:\n    - quay.io/securesign/timestamp-authority\n- source: registry.redhat.io/rhtas/trillian-createtree-rhel9\n  mirrors:\n    - quay.io/securesign/trillian-createtree\n- source: registry.redhat.io/rhtas/client-server-rhel9\n  mirrors:\n    - quay.io/securesign/client-server\n"
          - name: get-kubeconfig
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
            params:
              - name: eaasSpaceSecretRef
                value: $(tasks.provision-eaas-space.results.secretRef)
              - name: clusterName
                value: "$(steps.create-cluster.results.clusterName)"
              - name: credentials
                value: credentials
